### ISSUE TITLE
Use real routes for the privacy and terms of use

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-landing#11]
Looks like the gatsby router does not play nicely with S3 routing.
The issue seems to be caused by the urls not using trailing slashes. So we have Terms and conditions page at `/terms/index.html` but the url is `/terms` which looks for a file called `/terms.html` ...

**Comment by pyphilia** [comment]
Links are not working, this might help.

**Comment by spaenleh** [comment]
Done in #17
